### ISSUE TITLE
toy example error

### ISSUE THREAD

**Issue by plkmo** [kaituoxu/X-Punctuator#1]
Hi, I was trying to run your toy example script (run.sh) on windows bash and I received the following error. I have tried just train.py with the same arguments with the same error. I'm using PyTorch 1.2 so was wondering if its due to compatibility issue with 0.4. Thanks.

> Traceback (most recent call last):
>   File "C:/Users/tsd/Desktop/Python_Projects/DSL/Repositories/X-Punctuator/egs/toy/../../src/bin/train.py", line 84, in <module>
>     main(args)
>   File "C:/Users/tsd/Desktop/Python_Projects/DSL/Repositories/X-Punctuator/egs/toy/../../src/bin/train.py", line 78, in main
>     solver.train()
>   File "C:\Users\tsd\Desktop\Python_Projects\DSL\Repositories\X-Punctuator\src\solver\solver.py", line 77, in train
>     tr_avg_loss = self._run_one_epoch(epoch)
>   File "C:\Users\tsd\Desktop\Python_Projects\DSL\Repositories\X-Punctuator\src\solver\solver.py", line 181, in _run_one_epoch
>     pred = self.model(padded_input, input_lengths)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "C:\Users\tsd\Desktop\Python_Projects\DSL\Repositories\X-Punctuator\src\model\model.py", line 43, in forward
>     packed_output, _ = self.lstm(packed_input)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 562, in forward
>     return self.forward_packed(input, hx)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 554, in forward_packed
>     output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\rnn.py", line 529, in forward_impl
>     self.num_layers, self.dropout, self.training, self.bidirectional)
> TypeError: lstm() received an invalid combination of arguments - got (Tensor, Tensor, tuple, list, bool, int, float, bool, int), but expected one of:
>  * (Tensor data, Tensor batch_sizes, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional)
>       didn't match because some of the arguments have invalid types: (Tensor, Tensor, !tuple!, !list!, bool, int, float, bool, !int!)
>  * (Tensor input, tuple of Tensors hx, tuple of Tensors params, bool has_biases, int num_layers, float dropout, bool train, bool bidirectional, bool batch_first)
>       didn't match because some of the arguments have invalid types: (Tensor, !Tensor!, !tuple!, !list!, !bool!, int, !float!, bool, !int!)
>

**Comment by kaituoxu** [comment]
Yes, a PyTorch version issue.
Replace https://github.com/kaituoxu/X-Punctuator/blob/master/src/model/model.py#L25 with `bidirectional=bool(bidirectional))`

**Comment by plkmo** [comment]
thanks for your reply it works fine now!
